### ISSUE TITLE
quad_walk.m cannot run 

### ISSUE THREAD

**Issue by worasuch** [FrancescoScotti/Quadruped_gait_generation_ISMPC#1]
your gait generation is very interesting.
so, I try to run quad_walk.m but there is no function  **comput_one_feet_walk** and variable **init_quadruped2** defined.
could you please help with running this?

**Comment by FrancescoScotti** [comment]
I have uploaded the ultimate files right now. Let check that out and let me know :)

**Comment by worasuch** [comment]
Thank you so much! I can play with it now :)
